(ns com.yourtion.PatternDemo.example
  (:require [com.yourtion.Pattern01.person-example-ex :as p011])
  (:require [com.yourtion.Pattern01.person-example-ex :as p012])
  (:require [com.yourtion.Pattern02.person-example-cc :as p02])
  (:require [com.yourtion.Pattern03.cash-register :as p03])
  (:require [com.yourtion.Pattern04.person :as p04])
  (:require [com.yourtion.Pattern05.higher-order-functions :as p051])
  (:require [com.yourtion.Pattern05.lambda-bar-and-grille :as p052])
  (:require [com.yourtion.Pattern06.grade-reporter :as p06])
  (:require [com.yourtion.Pattern07.people-collector-example :as p07])
  (:require [com.yourtion.Pattern08.person-example :as p08])
  (:require [com.yourtion.Pattern09.calculator-example :as p09])
  (:require [com.yourtion.Pattern10.visitor-example :as p10])
  (:require [com.yourtion.Pattern11.services :as p11])
  (:require [com.yourtion.Pattern12.names :as p12])
  (:require [com.yourtion.Pattern13.mutual-recursion-example :as p13])
  (:require [com.yourtion.Pattern14.discount-example :as p14])
  (:require [com.yourtion.Pattern15.chain-example :as p15])
  (:require [com.yourtion.Pattern16.composition-examples :as p16])
  (:require [com.yourtion.Pattern17.memoization-example :as p17])
  (:require [com.yourtion.Pattern18.lazy-sequence-example :as p18])
  (:require [com.yourtion.Pattern19.focused-mutation-example :as p19])
  (:require [com.yourtion.Pattern20.flow-control-example :as p20])
  (:require [com.yourtion.Pattern21.dsl-example :as p21]))


(println)
(println "Pattern01 Example: ")
(println)
(p011/run)
(p012/run)
(println "------------------------------------")

(println)
(println "Pattern02 Example: ")
(println)
(p02/run)
(println "------------------------------------")

(println)
(println "Pattern03 Example: ")
(println)
(p03/run)
(println "------------------------------------")

(println)
(println "Pattern04 Example: ")
(println)
(p04/run)
(println "------------------------------------")

(println)
(println "Pattern05 Example: ")
(println)
(p051/run)
(p052/run)
(println "------------------------------------")

(println)
(println "Pattern06 Example: ")
(println)
(p06/run)
(println "------------------------------------")

(println)
(println "Pattern07 Example: ")
(println)
(p07/run)
(println "------------------------------------")

(println)
(println "Pattern08 Example: ")
(println)
(p08/run)
(println "------------------------------------")

(println)
(println "Pattern09 Example: ")
(println)
(p09/run)
(println "------------------------------------")

(println)
(println "Pattern10 Example: ")
(println)
(p10/run)
(println "------------------------------------")

(println)
(println "Pattern11 Example: ")
(println)
(p11/run)
(println "------------------------------------")

(println)
(println "Pattern12 Example: ")
(println)
(p12/run)
(println "------------------------------------")

(println)
(println "Pattern13 Example: ")
(println)
(p13/run)
(println "------------------------------------")

(println)
(println "Pattern14 Example: ")
(println)
(p14/run)
(println "------------------------------------")

(println)
(println "Pattern15 Example: ")
(println)
(p15/run)
(println "------------------------------------")

(println)
(println "Pattern16 Example: ")
(println)
(p16/run)
(println "------------------------------------")

(println)
(println "Pattern17 Example: ")
(println)
(p17/run)
(println "------------------------------------")

(println)
(println "Pattern18 Example: ")
(println)
(p18/run)
(println "------------------------------------")

(println)
(println "Pattern19 Example: ")
(println)
(p19/run)
(println "------------------------------------")

(println)
(println "Pattern20 Example: ")
(println)
(p20/run)
(println "------------------------------------")

(println)
(println "Pattern01 Example: ")
(println)
(p21/run)
(println "------------------------------------")

